## Fake news classifier

### data loading

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Final.csv')
df.head()

Unnamed: 0                                              title  \
0           0  Trump on Twitter (Feb 17) - Tom Price, Boeing,...   
1           1  Putin says Russia will respond if Russian medi...   
2           2  Rosie O’Donnell Thinks Martial Law is in Order...   
3           3   Chris Christie Reportedly Told Trump To Take ...   
4           4  STATE DEPT EMPLOYEE TAPPED TO OVERSEE HILLARY ...   

                                                text          subject  \
0  The following statements were posted to the ve...     politicsNews   
1  SOCHI, Russia (Reuters) - Russian President Vl...        worldnews   
2  21st Century Wire says Arguably irrelevant Hol...      Middle-east   
3  Sources say that Chris Christie was offered se...             News   
4  You seriously can t make up this stuff State D...  Government News   

                 date  info  
0  February 17, 2017      1  
1   October 19, 2017      1  
2    January 18, 2017     0  
3   December 11, 2016     0  
4         Sep 8, 2015     0

In [3]:
df = df.sample(frac = 1).reset_index(drop = True)
df.head()

Unnamed: 0                                              title  \
0       26917  Taiwan activist to be tried for subversion in ...   
1       10652  REPUBLICAN DEBATE LINE OF THE NIGHT: “Keep swi...   
2       39442  China punishes over 8,000 people for misuse of...   
3       42562  SHOCKING COMMENTS: Hillary Stirs The Pot Incit...   
4       15190  Venezuela has not told U.N. it is changing rep...   

                                                text    subject  \
0  Beijing (Reuters) - China will on Monday put o...  worldnews   
1  This is hysterical! I don t care who you suppo...   politics   
2  SHANGHAI (Reuters) - China has punished 8,123 ...  worldnews   
3  Hillary Clinton used a CNN interview on Friday...   politics   
4  NEW YORK (Reuters) - Venezuela s government ha...  worldnews   

                 date  info  
0  September 8, 2017      1  
1        Feb 25, 2016     0  
2  December 23, 2017      1  
3         Jul 9, 2016     0  
4  November 29, 2017      1

In [4]:
df.drop('Unnamed: 0', axis = 1, inplace = True)
df.head()

title  \
0  Taiwan activist to be tried for subversion in ...   
1  REPUBLICAN DEBATE LINE OF THE NIGHT: “Keep swi...   
2  China punishes over 8,000 people for misuse of...   
3  SHOCKING COMMENTS: Hillary Stirs The Pot Incit...   
4  Venezuela has not told U.N. it is changing rep...   

                                                text    subject  \
0  Beijing (Reuters) - China will on Monday put o...  worldnews   
1  This is hysterical! I don t care who you suppo...   politics   
2  SHANGHAI (Reuters) - China has punished 8,123 ...  worldnews   
3  Hillary Clinton used a CNN interview on Friday...   politics   
4  NEW YORK (Reuters) - Venezuela s government ha...  worldnews   

                 date  info  
0  September 8, 2017      1  
1        Feb 25, 2016     0  
2  December 23, 2017      1  
3         Jul 9, 2016     0  
4  November 29, 2017      1

In [5]:
df

title  \
0      Taiwan activist to be tried for subversion in ...   
1      REPUBLICAN DEBATE LINE OF THE NIGHT: “Keep swi...   
2      China punishes over 8,000 people for misuse of...   
3      SHOCKING COMMENTS: Hillary Stirs The Pot Incit...   
4      Venezuela has not told U.N. it is changing rep...   
...                                                  ...   
44893  Trump, Obama dominate Twitter year, but chicke...   
44894  Mattis says no change in U.S. policy to protec...   
44895  HERE’S HOW HILLARY’S VP PICK Has Just Proven H...   
44896          What Is Going On With The Secret Service?   
44897  After London setback, May wins Brexit cheer in...   

                                                    text       subject  \
0      Beijing (Reuters) - China will on Monday put o...     worldnews   
1      This is hysterical! I don t care who you suppo...      politics   
2      SHANGHAI (Reuters) - China has punished 8,123 ...     worldnews   
3      Hillary Clinton used a CNN interview on Friday...      politics   
4      NEW YORK (Reuters) - Venezuela s government ha...     worldnews   
...                                                  ...           ...   
44893  (Reuters) - U.S. President Donald Trump contin...  politicsNews   
44894  SEOUL (Reuters) - U.S. Defense Secretary Jim M...     worldnews   
44895  Hillary s VP pick is proving himself to be a a...      politics   
44896  21st Century Wire says This is a string of dis...   Middle-east   
44897  BRUSSELS (Reuters) - British Prime Minister Th...     worldnews   

                     date  info  
0      September 8, 2017      1  
1            Feb 25, 2016     0  
2      December 23, 2017      1  
3             Jul 9, 2016     0  
4      November 29, 2017      1  
...                   ...   ...  
44893   December 5, 2017      1  
44894   October 27, 2017      1  
44895        Jul 26, 2016     0  
44896      March 20, 2017     0  
44897  December 14, 2017      1  

[44898 rows x 5 columns]

In [6]:
df['info'].value_counts()

0    23481
1    21417
Name: info, dtype: int64

In [7]:
X = df.drop('info', axis = 1)
y = df['info']

### preprocessing the text

In [8]:
messages = X.copy()

In [10]:
import nltk
import re
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
corpus = []
ps = PorterStemmer()
for i in range(0, len(messages)) : 
    review = re.sub('^[a-zA-Z]', ' ', messages['title'][i])

    review = review.lower()
    review = review.split()

    review = [ps.stem(words) for words in review if not words in stopwords.words('english')]

    review = ' '.join(review)

    corpus.append(review)

In [13]:
corpus

["aiwan activist tri subvers china 'open' hear",
 'epublican debat line night: “keep swinging’ men, swing fences!” [video]',
 'hina punish 8,000 peopl misus govern funds: xinhua',
 'hock comments: hillari stir pot incit racial divid lie',
 'enezuela told u.n. chang representative: offici',
 '(video) judg jeanine: can’t trust hillari even think vote woman?',
 'vinc foster’ sister furiou donald trump',
 'hy obama approv $418 million sale u.s. weapon kenya last day office…and contract award firm never produc one planes?',
 'hot mic captur humili moment trump tell christi leav stage (video)',
 'hite hous spokesman spicer trump seek fix imag',
 'eb! bush discov secret america realli want president…and it’ someth never expect',
 'actbox: busi empir czech elect front-runn babi',
 'cuador judg order arrest vice presid odebrecht probe',
 'oscow say u.s. north korea start dialogue: ria',
 'reek centrist elect allianc leader boost popular',
 'ow! confirm ice: 5-time deport illeg alien protect san

In [14]:
X_final = np.array(corpus)
y_final = y

In [16]:
X_final.shape

(44898,)

In [18]:
y_final.shape

(44898,)

### word embedding

In [19]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [20]:
vocab_size = 10000
one_hot_rep = [one_hot(word, vocab_size) for word in corpus]

In [23]:
one_hot_rep = pad_sequences(one_hot_rep, maxlen = 30, padding = 'pre')

In [24]:
one_hot_rep

array([[   0,    0,    0, ..., 4316, 5779, 6111],
       [   0,    0,    0, ..., 7775,   37, 9042],
       [   0,    0,    0, ..., 1038, 6283, 1004],
       ...,
       [   0,    0,    0, ...,  554, 8686, 9054],
       [   0,    0,    0, ..., 8615,  219, 5861],
       [   0,    0,    0, ..., 2719,  906, 8855]])

In [25]:
X_final = np.array(one_hot_rep)

In [27]:
X_final.shape

(44898, 30)

In [28]:
y_final.shape

(44898,)

### train test split

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.25, random_state = 42)

In [30]:
print(f"{X_train.shape} :: {X_test.shape} :: {y_train.shape} :: {y_test.shape}")

(33673, 30) :: (11225, 30) :: (33673,) :: (11225,)


### model building and training

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Embedding, Dense, Dropout

In [45]:
model = Sequential([
    Embedding(input_dim = 10000, output_dim = 30, input_length = 30),
    Bidirectional(LSTM(64, return_sequences = True)),
    Dropout(0.3),
    Bidirectional(LSTM(32)),
    Dense(64, activation = 'relu'),
    Dense(1, activation = 'sigmoid')
])
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [46]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 30, 30)            300000    
                                                                 
 bidirectional_6 (Bidirectio  (None, 30, 128)          48640     
 nal)                                                            
                                                                 
 dropout_3 (Dropout)         (None, 30, 128)           0         
                                                                 
 bidirectional_7 (Bidirectio  (None, 64)               41216     
 nal)                                                            
                                                                 
 dense_6 (Dense)             (None, 64)                4160      
                                                                 
 dense_7 (Dense)             (None, 1)                

### model training and predictions

In [47]:
model.fit(X_train, y_train, epochs = 10, batch_size = 128, validation_split = 0.20)

Epoch 1/10
211/211 [==============================] - 17s 56ms/step - loss: 0.2379 - accuracy: 0.8944 - val_loss: 0.1241 - val_accuracy: 0.9512
Epoch 2/10
211/211 [==============================] - 10s 50ms/step - loss: 0.0791 - accuracy: 0.9715 - val_loss: 0.1128 - val_accuracy: 0.9558
Epoch 3/10
211/211 [==============================] - 11s 53ms/step - loss: 0.0510 - accuracy: 0.9828 - val_loss: 0.1339 - val_accuracy: 0.9541
Epoch 4/10
211/211 [==============================] - 10s 49ms/step - loss: 0.0323 - accuracy: 0.9903 - val_loss: 0.1393 - val_accuracy: 0.9550
Epoch 5/10
211/211 [==============================] - 10s 49ms/step - loss: 0.0211 - accuracy: 0.9936 - val_loss: 0.1696 - val_accuracy: 0.9528
Epoch 6/10
211/211 [==============================] - 10s 49ms/step - loss: 0.0121 - accuracy: 0.9968 - val_loss: 0.1678 - val_accuracy: 0.9569
Epoch 7/10
211/211 [==============================] - 10s 49ms/step - loss: 0.0123 - accuracy: 0.9962 - val_loss: 0.2098 - val_accuracy:

In [54]:
y_pred = model.predict(X_test)

351/351 [==============================] - 3s 6ms/step


In [55]:
y_pred = (y_pred > 0.5).astype(int)

In [56]:
y_pred

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [52]:
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [57]:
print(accuracy_score(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

0.9345211581291759
[[5739  556]
 [ 179 4751]]
              precision    recall  f1-score   support

           0       0.97      0.91      0.94      6295
           1       0.90      0.96      0.93      4930

    accuracy                           0.93     11225
   macro avg       0.93      0.94      0.93     11225
weighted avg       0.94      0.93      0.93     11225

